name: PR para develop

on:
  push:
    branches:
      - 'feature/*'
      - 'fix/*'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checar repositório
        uses: actions/checkout@v4


      - name: Criar PR para develop
        run: |
          gh pr create \
            --title "PR Gerada Automaticamente - $(basename $GITHUB_REF) -> develop" \
            --body "Auto PR gerada pelo push" \
            --base develop \
            --head ${GITHUB_REF#refs/heads/}
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

