name: PR para develop

on:
  push:
    branches:
      - 'feature/*'
      - 'fix/*'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checar repositório
        uses: actions/checkout@v4


  - name: Criar PR develop → release
        run: |
          gh pr create \
            --title "Release ${RELEASE_VERSION} - Desenvolvimento → Release" \
            --body "PR automática contendo as alterações da develop para release/${RELEASE_VERSION}\n\n**Atenção:** Não fazer merge desta PR, apenas revisar as alterações." \
            --base release/${RELEASE_VERSION} \
            --head develop
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}