name: Criar branch release e PR develop → release

on:
  pull_request:
    branches:
      - develop
    types: [closed]

jobs:
  create-release-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checar repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: Calcular próxima versão release
        id: next_version
        run: |
          # Buscar branches remotas release/*
          git fetch --prune origin '+refs/heads/release/*:refs/remotes/origin/release/*'

          # Contar quantas branches release existem
          count=$(git branch -r | grep 'origin/release/' | wc -l)

          # Incrementar
          next=$((count + 1))

          echo "branches release existentes: $count"
          echo "próxima versão: $next"

          echo "RELEASE_VERSION=$next" >> $GITHUB_ENV

      - name: Criar branch release a partir da develop
        run: |
          git checkout develop
          git pull origin develop
          git checkout -b release/${{ env.RELEASE_VERSION }}
          git push origin release/${{ env.RELEASE_VERSION }}

      - name: Instalar GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Criar PR develop → release
        id: create_pr
        run: |
          gh pr create \
            --title "Release ${{ env.RELEASE_VERSION }} (Automática)" \
            --body "PR automática da develop para release/${{ env.RELEASE_VERSION }}" \
            --base release/${{ env.RELEASE_VERSION }} \
            --head develop
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}