name: Criar branch release e PR develop → release

on:
  pull_request:
    branches:
      - develop
    types: [closed]

jobs:
  create-release-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      
    steps:
      - name: Checar repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: Calcular próxima versão release
        id: next_version
        run: |
          git fetch --prune origin '+refs/heads/release/*:refs/remotes/origin/release/*'
          count=$(git branch -r | grep 'origin/release/' | wc -l)
          next=$((count + 1))
          echo "branches release existentes: $count"
          echo "próxima versão: $next"
          echo "RELEASE_VERSION=$next" >> $GITHUB_ENV

      - name: Criar branch release
        run: |
          git checkout develop
          git pull origin develop
          git checkout -b release/${{ env.RELEASE_VERSION }}
          git push origin release/${{ env.RELEASE_VERSION }}

  create-release-pr:
    needs: create-release-branch
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      
    steps:
      - name: Checar repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: develop

      - name: Instalar GitHub CLI
        run: |
          type -p curl >/dev/null || sudo apt install curl -y
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y

      - name: Criar PR usando API REST
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -d '{
              "title": "Release ${{ needs.create-release-branch.outputs.RELEASE_VERSION }} (Automática)",
              "body": "PR automática da develop para release/${{ needs.create-release-branch.outputs.RELEASE_VERSION }}",
              "head": "develop",
              "base": "release/${{ needs.create-release-branch.outputs.RELEASE_VERSION }}"
            }'