name: Criar release/N+1 a partir da develop

on:
  push:
    branches:
      - develop

jobs:
  create-release-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checar repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # necessário para pegar todas as branches remotas

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: Obter próximo número da release
        id: next_release
        run: |
          git fetch origin

          # Filtrar apenas branches release/N
          RELEASE_BRANCHES=$(git ls-remote --heads origin "release/*" | awk -F'/' '{print $3}')
          
          # Extrair apenas os números das releases
          NUMEROS=$(echo "$RELEASE_BRANCHES" | grep -Eo '[0-9]+' | sort -n)

          # Pegar o maior número existente
          if [ -z "$NUMEROS" ]; then
            NEXT=1
          else
            NEXT=$(echo "$NUMEROS" | tail -n 1)
            NEXT=$((NEXT + 1))
          fi

          echo "PRÓXIMA RELEASE: release/$NEXT"
          echo "RELEASE_BRANCH=release/$NEXT" >> $GITHUB_ENV

      - name: Criar e fazer push da nova release
        run: |
          git checkout develop
          git pull origin develop
          
          git checkout -b $RELEASE_BRANCH
          git push origin $RELEASE_BRANCH
        env:
          RELEASE_BRANCH: ${{ env.RELEASE_BRANCH }}
