name: PR release → main após merge com develop

on:
  pull_request:
    branches:
      - 'release/*'
    types: [closed]

jobs:
  merge-develop-into-release-and-create-main-pr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checar repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: Descobrir nome da branch release
        id: vars
        run: |
          RELEASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          echo "RELEASE_BRANCH=$RELEASE_BRANCH" >> $GITHUB_ENV
          echo "Release branch detectada: $RELEASE_BRANCH"

      - name: Merge develop → release/{version}
        run: |
          git fetch origin
          git checkout $RELEASE_BRANCH
          git merge origin/develop --no-ff -m "Merge develop into $RELEASE_BRANCH"
          git push origin $RELEASE_BRANCH

      - name: Criar PR release → main
        run: |
          gh pr create \
            --title "PR Gerada Automaticamente - $RELEASE_BRANCH -> main" \
            --body "PR automática para promover a release `${RELEASE_BRANCH}` para a branch main.\n\nRevisar com atenção antes de aprovar." \
            --base main \
            --head $RELEASE_BRANCH
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
<<<<<<< HEAD

      - name: Fazer merge automático da release na main
        run: |
          gh pr merge "$PR_URL" --merge --delete-branch
        env:
          GH

=======
>>>>>>> 8cc1db33f72817871d4db382bdcaab0670de8819
