name: Verificar merge para main

on:
  push:
    branches:
      - 'main'

jobs:
  check-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checar repositório
        uses: actions/checkout@v4

      - name: Verificar se merge ocorreu corretamente
        run: |
          # Verifica se há conflitos de merge (arquivos não resolvidos)
          if git ls-files -u | grep .; then
            echo "Conflitos de merge detectados!"
            exit 1
          else
            echo "Merge realizado com sucesso, sem conflitos."
          fi
